import type { ClientContext } from '@deepseek-ai/dsh-client-runtime/client'
import type { ModelProviderGroup, SettingsNamespaceView } from '@deepseek-ai/dsh-api-remotes/client'
import type {} from '@deepseek-ai/dsh-client-ui-settings/client'
import type {} from '@deepseek-ai/dsh-client-ui-conversation/client'
import type {} from '@deepseek-ai/dsh-client-ui-slots'
import { Button, IconDataOutline16, IconRefreshOutline16, Input, StateDot } from '@deepseek-ai/dsh-client-ui-primitives'
import { useEffect, useMemo, useState } from 'react'

const NS = 'llm-verifier'
interface Values { enabled: boolean; provider: string; model: string; reasoningEffort?: string; maxTokens: number; maxConcurrency: number; maxRetries: number; timeoutMs: number; cacheMaxEntries: number; estimatedInputUsdPerMillion: number; estimatedOutputUsdPerMillion: number }
interface Loaded { groups: ModelProviderGroup[]; settings: SettingsNamespaceView; writable: boolean; failures: string[] }
interface RunStats { calls: number; attempts: number; retries: number; inputTokens: number; cachedInputTokens: number; outputTokens: number; reasoningTokens: number; cacheHits: number; cacheMisses: number; estimatedCostUsd: number; topLogprobScores: number; explicitTagScores: number }
interface InvocationRecord { id: string; toolName: string; sessionId?: string; startedAt: number; finishedAt: number; durationMs: number; success: boolean; errorName?: string; errorMessage?: string; provider: string; model: string; stats: RunStats }
interface DailyStatistics { date: string; invocations: number; successes: number; failures: number; calls: number; tokens: number; estimatedCostUsd: number; byTool: Record<string, number> }
interface ToolStatistics { toolName: string; invocations: number; successes: number; failures: number; successRate: number; averageDurationMs: number; calls: number; tokens: number; cacheHits: number; cacheMisses: number; estimatedCostUsd: number }
interface ModelStatistics { provider: string; model: string; invocations: number; calls: number; tokens: number; estimatedCostUsd: number }
interface Totals extends RunStats { invocations: number; successes: number; failures: number; successRate: number; averageDurationMs: number; tokens: number; cacheHitRate: number }
interface StatisticsOverview { generatedAt: number; fromMs: number; toMs: number; sessionId?: string; totals: Totals; daily: DailyStatistics[]; tools: ToolStatistics[]; models: ModelStatistics[]; recent: InvocationRecord[] }
interface StatisticsPageProps { sessionId: string; rpc: { call(channel: string, endpoint: string, payload: unknown, signal?: AbortSignal): Promise<{ ok: boolean; value?: unknown; error?: { message: string } }> } }

const shell: React.CSSProperties = { display: 'flex', flexDirection: 'column', gap: 18, padding: '8px 4px 32px', color: 'var(--dsw-text-primary)' }
const card: React.CSSProperties = { display: 'flex', flexDirection: 'column', gap: 0, padding: '16px 16px 0', border: '1px solid var(--dsw-alias-border-l2, rgba(255, 255, 255, 0.16))', borderRadius: 12, background: 'var(--dsw-alias-bg-module, rgba(20, 31, 57, 0.42))', overflow: 'hidden' }
const sectionTitle: React.CSSProperties = { display: 'flex', gap: 10, alignItems: 'center', padding: '0 0 12px', borderBottom: '1px solid var(--dsw-alias-border-l2, rgba(255, 255, 255, 0.16))' }
const row: React.CSSProperties = { display: 'grid', gridTemplateColumns: 'minmax(150px, 1fr) minmax(220px, 1.4fr)', gap: 18, alignItems: 'center', padding: '14px 0', borderBottom: '1px solid var(--dsw-alias-border-l2, rgba(255, 255, 255, 0.16))' }
const selectStyle: React.CSSProperties = { width: '100%', minHeight: 38, padding: '0 12px', borderRadius: 10, color: 'var(--dsw-text-primary)', background: 'var(--dsw-surface-sunken)', border: '1px solid var(--dsw-alias-border-l2, rgba(255, 255, 255, 0.16))' }
const dashboardCard: React.CSSProperties = { border: '1px solid var(--dsw-alias-border-l2, rgba(255,255,255,.13))', background: 'color-mix(in srgb, var(--dsw-alias-bg-module, #171925) 88%, transparent)', borderRadius: 16, boxShadow: '0 12px 36px rgba(0,0,0,.12)' }
const muted: React.CSSProperties = { color: 'var(--dsw-text-secondary)', fontSize: 12 }
const toolLabels: Record<string, string> = { verifier_compare: '两项对比', verifier_select: '多项优选', verifier_track: '进度跟踪', verifier_current_session: '会话验收' }
const toolColors: Record<string, string> = { verifier_compare: '#4f8cff', verifier_select: '#8b6df6', verifier_track: '#2fc5c9', verifier_current_session: '#f5a524' }

function record(value: unknown): Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {} }
function values(view: SettingsNamespaceView): Values { const v=record(view.value); return { enabled:v.enabled!==false,provider:String(v.provider??''),model:String(v.model??''),...(typeof v.reasoningEffort==='string'?{reasoningEffort:v.reasoningEffort}:{}),maxTokens:Number(v.maxTokens??32768),maxConcurrency:Number(v.maxConcurrency??8),maxRetries:Number(v.maxRetries??3),timeoutMs:Number(v.timeoutMs??300000),cacheMaxEntries:Number(v.cacheMaxEntries??10000),estimatedInputUsdPerMillion:Number(v.estimatedInputUsdPerMillion??0),estimatedOutputUsdPerMillion:Number(v.estimatedOutputUsdPerMillion??0) } }
function message(error: unknown): string { return error instanceof Error ? error.message : String(error) }
function Label({title,help}:{title:string;help:string}) { return <div><div style={{fontWeight:600}}>{title}</div><div style={{fontSize:12,color:'var(--dsw-text-secondary)',marginTop:3}}>{help}</div></div> }
function compact(value: number): string { return new Intl.NumberFormat('zh-CN', { notation: value >= 10_000 ? 'compact' : 'standard', maximumFractionDigits: value >= 1_000 ? 1 : 0 }).format(value) }
function money(value: number): string { return '$' + value.toLocaleString('en-US', { minimumFractionDigits: value < 0.01 ? 4 : 2, maximumFractionDigits: value < 0.01 ? 4 : 2 }) }
function duration(value: number): string { if (value < 1000) return Math.round(value) + ' ms'; if (value < 60_000) return (value / 1000).toFixed(1) + ' s'; return (value / 60_000).toFixed(1) + ' min' }
function dateTime(value: number): string { return new Intl.DateTimeFormat('zh-CN', { month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit' }).format(value) }
function startOfRange(days: number): number { const date = new Date(); date.setHours(0,0,0,0); date.setDate(date.getDate() - days + 1); return date.getTime() }
function endOfToday(): number { const date = new Date(); date.setHours(0,0,0,0); date.setDate(date.getDate() + 1); return date.getTime() }

function VerifierSettings({ api }:{api:any}) {
  const [loaded,setLoaded]=useState<Loaded|null>(null); const [draft,setDraft]=useState<Values|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [saved,setSaved]=useState(false)
  const load=async()=>{setError(null);try{const [m,s]=await Promise.all([api.llm.models({}),api.settings.describe({})]);if(!m.result.ok)throw new Error(m.result.error.message);if(!s.result.ok)throw new Error(s.result.error.message);const view=s.result.value.namespaces.find((x:SettingsNamespaceView)=>x.ns===NS);if(!view)throw new Error('Verifier settings namespace is not registered. Restart the DSH host.');const next={groups:m.result.value.groups,settings:view,writable:s.result.value.writable,failures:m.result.value.failures.map((f:any)=>f.name+': '+f.message)};setLoaded(next);setDraft(values(view))}catch(e){setError(message(e))}}
  useEffect(()=>{void load()},[])
  const models=useMemo(()=>loaded?.groups.find(g=>g.id===draft?.provider)?.models??[],[loaded,draft?.provider])
  const selected=models.find(m=>m.id===draft?.model); const efforts=selected?.reasoning?.efforts??[]
  const patch=<K extends keyof Values>(key:K,value:Values[K])=>setDraft(v=>v?{...v,[key]:value}:v)
  const save=async()=>{if(!loaded||!draft)return;setBusy(true);setSaved(false);setError(null);try{const section={...record(loaded.settings.user),...draft};if(!draft.reasoningEffort)delete section.reasoningEffort;const res=await api.settings.update({ns:NS,patch:section,expectedRevision:loaded.settings.revision});if(!res.result.ok)throw new Error(res.result.error.message);setLoaded(v=>v?{...v,settings:res.result.value}:v);setDraft(values(res.result.value));setSaved(true)}catch(e){setError(message(e))}finally{setBusy(false)}}
  if(!loaded||!draft)return <div style={shell}><h2>LLM Verifier</h2><p>{error??'正在读取 DSH 模型和设置…'}</p>{error&&<Button onClick={()=>void load()}>重试</Button>}</div>
  const numeric=(key:keyof Values,min=0)=><Input type="number" min={min} value={String(draft[key])} onChange={e=>patch(key,Number(e.target.value) as never)} />
  return <div style={shell}>
    <div><h2 style={{margin:'0 0 6px'}}>LLM Verifier</h2><p style={{margin:0,color:'var(--dsw-text-secondary)'}}>选择任意已在 DSH「模型」页配置并启用的模型作为独立裁判。设置实时生效。</p></div>
    <div style={card}><div style={sectionTitle}><StateDot state={draft.enabled?'done':'error'}/><strong>工具开关</strong></div>
      <div style={row}><Label title="启用 Verifier 工具" help={draft.enabled?'四个 verifier 工具可被 Agent 调用，每次调用会向裁判模型发起请求。':'已停用：Agent 调用 verifier 工具会立即返回错误，不产生任何模型请求。'}/><button onClick={()=>patch('enabled',!draft.enabled)} style={{width:80,height:32,borderRadius:16,border:'1px solid var(--dsw-alias-border-l2, rgba(255,255,255,0.16))',background:draft.enabled?'var(--dsw-success, #2f9e5b)':'var(--dsw-surface-sunken)',color:'#fff',cursor:'pointer',fontSize:13,fontWeight:600}}>{draft.enabled?'已启用':'已停用'}</button></div>
      {!draft.enabled&&<div style={{padding:'0 0 14px',fontSize:12,color:'var(--dsw-state-warn-primary, #d9a441)'}}>⚠ 当前停用 verifier_compare / verifier_select / verifier_track / verifier_current_session 四个工具</div>}
    </div>
    <div style={card}><div style={sectionTitle}><StateDot state="done"/><strong>裁判模型</strong></div>
      <div style={row}><Label title="供应商" help="只显示当前 DSH 中可路由的供应商"/><select style={selectStyle} value={draft.provider} onChange={e=>{const provider=e.target.value;const first=loaded.groups.find(g=>g.id===provider)?.models[0];setDraft({...draft,provider,...(first?{model:first.id,reasoningEffort:first.reasoning?.defaultEffort}:{})})}}>{loaded.groups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.id}</option>)}</select></div>
      <div style={row}><Label title="模型" help="模型目录来自 DSH adapter，选择结果会持久化"/><select style={selectStyle} value={draft.model} onChange={e=>{const model=e.target.value;const found=models.find(m=>m.id===model);setDraft({...draft,model,...(found?.reasoning?.defaultEffort?{reasoningEffort:found.reasoning.defaultEffort}:{reasoningEffort:undefined})})}}>{models.map(m=><option key={m.id} value={m.id}>{m.name} · {m.id}</option>)}</select></div>
      <div style={row}><Label title="推理强度" help="由所选模型 adapter 声明；留空使用模型默认值"/><select style={selectStyle} value={draft.reasoningEffort??''} onChange={e=>patch('reasoningEffort',e.target.value||undefined)}><option value="">模型默认</option>{efforts.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></div>
      <div style={row}><Label title="最大输出 Token" help="每个裁判请求的输出上限"/>{numeric('maxTokens',1)}</div>
    </div>
    <div style={card}><div style={sectionTitle}><strong>执行控制</strong></div><div style={row}><Label title="最大并发" help="所有 verifier 工具共享的请求并发上限"/>{numeric('maxConcurrency',1)}</div><div style={row}><Label title="最多重试" help="短暂网络、限流和服务端错误的重试次数"/>{numeric('maxRetries',0)}</div><div style={row}><Label title="请求超时（毫秒）" help="单个模型请求的超时时间"/>{numeric('timeoutMs',1)}</div><div style={row}><Label title="缓存条目上限" help="持久评分缓存保留的最大条目数"/>{numeric('cacheMaxEntries',1)}</div></div>
    <div style={card}><div style={sectionTitle}><strong>费用估算（每百万 Token，USD）</strong></div><div style={row}><Label title="输入价格" help="仅用于结果中的 estimatedCostUsd"/>{numeric('estimatedInputUsdPerMillion',0)}</div><div style={row}><Label title="输出价格" help="仅用于结果中的 estimatedCostUsd"/>{numeric('estimatedOutputUsdPerMillion',0)}</div></div>
    {loaded.failures.length>0&&<div style={{...card,borderColor:'var(--dsw-alias-state-warn-primary, #d9a441)',paddingBottom:16}}><strong>部分模型目录读取失败</strong>{loaded.failures.map(x=><div key={x}>{x}</div>)}</div>}
    {error&&<div style={{color:'var(--dsw-danger)'}}>{error}</div>}{saved&&<div style={{color:'var(--dsw-success)'}}>已保存，后续 verifier 调用将使用新设置。</div>}
    <div style={{display:'flex',gap:10}}><Button disabled={busy||!loaded.writable} onClick={()=>void save()}>{busy?'保存中…':'保存设置'}</Button><Button variant="outline" disabled={busy} onClick={()=>void load()}>重新载入</Button></div>
  </div>
}

function Metric({ label, value, note, accent }:{label:string;value:string;note:string;accent?:string}) {
  return <div style={{...dashboardCard,padding:'16px 18px',minWidth:0}}><div style={muted}>{label}</div><div style={{fontSize:25,fontWeight:750,lineHeight:1.2,margin:'7px 0 5px',color:accent}}>{value}</div><div style={{...muted,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{note}</div></div>
}

function TrendChart({ daily, days }:{daily:DailyStatistics[];days:number}) {
  const rows=useMemo(()=>{const map=new Map(daily.map(row=>[row.date,row]));const values:DailyStatistics[]=[];const start=new Date(startOfRange(days));for(let i=0;i<days;i+=1){const date=new Date(start);date.setDate(start.getDate()+i);const key=[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');values.push(map.get(key)??{date:key,invocations:0,successes:0,failures:0,calls:0,tokens:0,estimatedCostUsd:0,byTool:{}})}return values},[daily,days])
  const width=760,height=230,pad={l:44,r:24,t:20,b:38};const innerW=width-pad.l-pad.r,innerH=height-pad.t-pad.b
  const max=Math.max(1,...rows.flatMap(row=>[row.invocations,row.calls]));const x=(index:number)=>pad.l+(rows.length<=1?innerW/2:index*innerW/(rows.length-1));const y=(value:number)=>pad.t+innerH-value/max*innerH
  const points=rows.map((row,index)=>`${x(index)},${y(row.calls)}`).join(' ');const step=rows.length>16?Math.ceil(rows.length/7):Math.max(1,Math.ceil(rows.length/7));const barWidth=Math.max(3,Math.min(18,innerW/Math.max(rows.length,1)*.55))
  return <div style={{width:'100%',overflowX:'auto'}}><svg viewBox={`0 0 ${width} ${height}`} style={{display:'block',width:'100%',minWidth:620,height:'auto'}} aria-label="每日工具调用与模型请求趋势">
    {[0,.25,.5,.75,1].map(ratio=><g key={ratio}><line x1={pad.l} x2={width-pad.r} y1={pad.t+innerH*ratio} y2={pad.t+innerH*ratio} stroke="rgba(148,163,184,.16)"/><text x={pad.l-8} y={pad.t+innerH*ratio+4} textAnchor="end" fontSize="10" fill="var(--dsw-text-secondary)">{Math.round(max*(1-ratio))}</text></g>)}
    {rows.map((row,index)=><rect key={row.date} x={x(index)-barWidth/2} y={y(row.invocations)} width={barWidth} height={pad.t+innerH-y(row.invocations)} rx="2" fill="#4f8cff" opacity=".82"/>)}
    <polyline points={points} fill="none" stroke="#5ed7e8" strokeWidth="2.4" strokeLinejoin="round" strokeLinecap="round"/>
    {rows.map((row,index)=>index%step===0||index===rows.length-1?<text key={row.date} x={x(index)} y={height-14} textAnchor="middle" fontSize="10" fill="var(--dsw-text-secondary)">{Number(row.date.slice(5,7))}/{Number(row.date.slice(8,10))}</text>:null)}
  </svg><div style={{display:'flex',justifyContent:'center',gap:18,...muted}}><span><i style={{display:'inline-block',width:8,height:8,borderRadius:2,background:'#4f8cff',marginRight:6}}/>工具调用</span><span><i style={{display:'inline-block',width:14,height:2,background:'#5ed7e8',marginRight:6,verticalAlign:'middle'}}/>模型请求</span></div></div>
}

function StatisticsPage({ sessionId, rpc }:StatisticsPageProps) {
  const [days,setDays]=useState(30);const [sessionOnly,setSessionOnly]=useState(false);const [data,setData]=useState<StatisticsOverview|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [refresh,setRefresh]=useState(0)
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);void rpc.call('/llm-verifier','statistics',{fromMs:startOfRange(days),toMs:endOfToday(),timezoneOffsetMinutes:new Date().getTimezoneOffset(),recentLimit:50,...(sessionOnly?{sessionId:String(sessionId)}:{})},controller.signal).then(result=>{if(!result.ok)throw new Error(result.error?.message??'统计接口请求失败');setData(result.value as StatisticsOverview)},cause=>{if(!controller.signal.aborted)throw cause}).catch(cause=>{if(!controller.signal.aborted)setError(message(cause))}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[days,sessionOnly,sessionId,refresh,rpc])
  const totals=data?.totals
  return <main style={{height:'100%',overflow:'auto',boxSizing:'border-box',padding:'22px clamp(16px, 3vw, 38px) 48px',color:'var(--dsw-text-primary)',background:'radial-gradient(circle at 10% 0%, rgba(115,77,255,.09), transparent 32%), radial-gradient(circle at 100% 8%, rgba(47,197,201,.07), transparent 28%)'}}>
    <div style={{maxWidth:1180,margin:'0 auto',display:'flex',flexDirection:'column',gap:16}}>
      <header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,flexWrap:'wrap'}}><div><div style={{display:'flex',alignItems:'center',gap:10}}><span style={{display:'grid',placeItems:'center',width:34,height:34,borderRadius:10,background:'rgba(79,140,255,.14)',color:'#6da0ff'}}><IconDataOutline16 size={18}/></span><h2 style={{margin:0,fontSize:23}}>Verifier 工具统计</h2></div><p style={{margin:'7px 0 0 44px',...muted}}>数据更新于 {data?dateTime(data.generatedAt):'--'} · 自动记录四个验证工具的实际执行结果</p></div>
        <div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><div style={{display:'flex',padding:3,borderRadius:10,background:'var(--dsw-surface-sunken)',border:'1px solid var(--dsw-alias-border-l2, rgba(255,255,255,.12))'}}>{[7,30,90].map(value=><button key={value} onClick={()=>setDays(value)} style={{border:0,borderRadius:7,padding:'6px 10px',cursor:'pointer',color:days===value?'#fff':'var(--dsw-text-secondary)',background:days===value?'#3f68d8':'transparent'}}>{value} 天</button>)}</div><button onClick={()=>setSessionOnly(value=>!value)} style={{border:'1px solid var(--dsw-alias-border-l2, rgba(255,255,255,.15))',borderRadius:9,padding:'7px 11px',cursor:'pointer',color:'var(--dsw-text-primary)',background:sessionOnly?'rgba(79,140,255,.18)':'var(--dsw-surface-sunken)'}}>{sessionOnly?'当前会话':'全部会话'}</button><button title="刷新" onClick={()=>setRefresh(value=>value+1)} style={{display:'grid',placeItems:'center',width:34,height:34,borderRadius:9,border:'1px solid var(--dsw-alias-border-l2, rgba(255,255,255,.15))',color:'var(--dsw-text-primary)',background:'var(--dsw-surface-sunken)',cursor:'pointer'}}><IconRefreshOutline16 size={16}/></button></div>
      </header>
      {error&&<div style={{...dashboardCard,padding:18,borderColor:'var(--dsw-danger, #e85858)',color:'var(--dsw-danger, #e85858)'}}>{error}<div style={{...muted,marginTop:6}}>请确认宿主已重启并加载最新版本的 dsh-llm-verifier。</div></div>}
      {loading&&!data?<div style={{...dashboardCard,padding:32,textAlign:'center',...muted}}>正在读取工具运行统计…</div>:<>
        <section style={{...dashboardCard,padding:'22px 24px',display:'grid',gridTemplateColumns:'minmax(220px,1.4fr) minmax(240px,1fr)',gap:24,alignItems:'center'}}><div><div style={muted}>{days} 天估算费用</div><div style={{fontSize:38,fontWeight:780,letterSpacing:'-.03em',margin:'5px 0'}}>{money(totals?.estimatedCostUsd??0)}</div><div style={muted}>{compact(totals?.invocations??0)} 次工具调用 · {compact(totals?.calls??0)} 次裁判模型请求</div></div><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:'9px 16px',fontSize:13}}><span style={muted}>成功调用</span><strong>{compact(totals?.successes??0)} <small style={{color:'#77d49b'}}>▲ {((totals?.successRate??0)*100).toFixed(1)}%</small></strong><span style={muted}>失败调用</span><strong>{compact(totals?.failures??0)}</strong><span style={muted}>平均耗时</span><strong>{duration(totals?.averageDurationMs??0)}</strong></div></section>
        <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><Metric label="缓存命中率" value={((totals?.cacheHitRate??0)*100).toFixed(1)+'%'} note={`${compact(totals?.cacheHits??0)} 命中 / ${compact((totals?.cacheHits??0)+(totals?.cacheMisses??0))} 评分`} accent="#b7dd64"/><Metric label="Token" value={compact(totals?.tokens??0)} note={`输入 ${compact((totals?.inputTokens??0)+(totals?.cachedInputTokens??0))} · 输出 ${compact(totals?.outputTokens??0)}`}/><Metric label="平均模型请求" value={(totals?.invocations??0)>0?((totals?.calls??0)/(totals?.invocations??1)).toFixed(1):'0'} note={`${compact(totals?.attempts??0)} 次尝试 · ${compact(totals?.retries??0)} 次重试`}/><Metric label="评分模式" value={compact(totals?.topLogprobScores??0)} note={`Top-logprobs · 显式标签 ${compact(totals?.explicitTagScores??0)}`}/></section>
        <section style={{...dashboardCard,padding:'18px 20px 16px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:4}}><strong>每日工具调用与模型请求趋势</strong><span style={muted}>{sessionOnly?'当前会话':'全部会话'}</span></div><TrendChart daily={data?.daily??[]} days={days}/></section>
        <section style={{...dashboardCard,padding:'18px 18px 8px',overflow:'hidden'}}><div style={{display:'flex',justifyContent:'space-between',margin:'0 2px 12px'}}><strong>工具运行明细</strong><span style={muted}>{data?.tools.length??0} 类工具</span></div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13,minWidth:760}}><thead><tr style={{textAlign:'left',color:'var(--dsw-text-secondary)',background:'var(--dsw-surface-sunken)'}}>{['工具','调用','成功率','平均耗时','模型请求','Token','缓存命中','估算费用'].map(value=><th key={value} style={{padding:'10px 12px',fontWeight:500}}>{value}</th>)}</tr></thead><tbody>{(data?.tools??[]).map(tool=><tr key={tool.toolName} style={{borderTop:'1px solid var(--dsw-alias-border-l2, rgba(255,255,255,.1))'}}><td style={{padding:'13px 12px'}}><span style={{display:'inline-block',width:8,height:8,borderRadius:'50%',background:toolColors[tool.toolName]??'#8691a8',marginRight:8}}/><strong>{toolLabels[tool.toolName]??tool.toolName}</strong><div style={{...muted,margin:'3px 0 0 16px'}}>{tool.toolName}</div></td><td style={{padding:'13px 12px'}}>{compact(tool.invocations)}</td><td style={{padding:'13px 12px',color:tool.successRate>=.9?'#77d49b':tool.successRate>=.7?'#e3bd63':'#ed7777'}}>{(tool.successRate*100).toFixed(1)}%</td><td style={{padding:'13px 12px'}}>{duration(tool.averageDurationMs)}</td><td style={{padding:'13px 12px'}}>{compact(tool.calls)}</td><td style={{padding:'13px 12px'}}>{compact(tool.tokens)}</td><td style={{padding:'13px 12px'}}>{tool.cacheHits}/{tool.cacheHits+tool.cacheMisses}</td><td style={{padding:'13px 12px'}}>{money(tool.estimatedCostUsd)}</td></tr>)}{(data?.tools.length??0)===0&&<tr><td colSpan={8} style={{padding:28,textAlign:'center',...muted}}>所选范围内还没有 Verifier 工具调用。后续执行会自动出现在这里。</td></tr>}</tbody></table></div></section>
        <section style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(290px,.45fr)',gap:16,alignItems:'start'}}><div style={{...dashboardCard,padding:'18px 18px 8px',overflow:'hidden'}}><div style={{display:'flex',justifyContent:'space-between',margin:'0 2px 12px'}}><strong>最近调用</strong><span style={muted}>最多 50 条</span></div><div style={{maxHeight:360,overflow:'auto'}}>{(data?.recent??[]).map(item=><div key={item.id} style={{display:'grid',gridTemplateColumns:'minmax(170px,1fr) auto',gap:12,padding:'11px 8px',borderTop:'1px solid var(--dsw-alias-border-l2, rgba(255,255,255,.1))'}}><div><div style={{display:'flex',alignItems:'center',gap:8}}><span style={{width:7,height:7,borderRadius:'50%',background:item.success?'#59c985':'#e76565'}}/><strong style={{fontSize:13}}>{toolLabels[item.toolName]??item.toolName}</strong><span style={muted}>{item.provider}/{item.model}</span></div>{!item.success&&<div title={item.errorMessage} style={{margin:'5px 0 0 15px',fontSize:11,color:'#e76565',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{item.errorMessage??item.errorName}</div>}</div><div style={{textAlign:'right'}}><div style={{fontSize:12}}>{duration(item.durationMs)}</div><div style={{...muted,marginTop:3}}>{dateTime(item.startedAt)}</div></div></div>)}{(data?.recent.length??0)===0&&<div style={{padding:24,textAlign:'center',...muted}}>暂无记录</div>}</div></div>
          <div style={{...dashboardCard,padding:'18px'}}><strong>模型汇总</strong><div style={{marginTop:10,display:'flex',flexDirection:'column',gap:10}}>{(data?.models??[]).map(model=><div key={model.provider+'\0'+model.model} style={{padding:'11px 12px',borderRadius:10,background:'var(--dsw-surface-sunken)'}}><div style={{fontWeight:650,fontSize:13,overflow:'hidden',textOverflow:'ellipsis'}}>{model.model}</div><div style={{...muted,marginTop:3}}>{model.provider}</div><div style={{display:'flex',justifyContent:'space-between',marginTop:9,fontSize:12}}><span>{compact(model.calls)} 请求</span><span>{compact(model.tokens)} Token</span><strong>{money(model.estimatedCostUsd)}</strong></div></div>)}{(data?.models.length??0)===0&&<div style={muted}>暂无模型调用</div>}</div></div></section>
      </>}
    </div>
  </main>
}

export const inject=['slots','connection']
export function apply(ctx:ClientContext):void {
  const connection=ctx.get('connection') as any
  ctx.slots.inject('settings.section',()=>ctx.slots.register({name:'settings.section',id:'llm-verifier',order:35,label:'LLM Verifier',inject:()=>({api:connection.api})},VerifierSettings as never))
  ctx.slots.inject('conversation.view',()=>ctx.slots.register({name:'conversation.view',id:'llm-verifier-statistics',order:30,label:'工具统计',inject:()=>({rpc:connection.rpc})},StatisticsPage as never))
}
